### ISSUE TITLE
Missing module

### ISSUE THREAD

**Issue by LaserTron** [ninapavlich/doxie-automator#4]
`main.py` imports `Trainer` from `doxieautomator.train` but there is currently no `train.py` module.

**Comment by ninapavlich** [comment]
Hey @LaserTron sorry this project is not functional yet, I'll make a note in the README

**Comment by LaserTron** [comment]
Okay. Good luck! This is a cool project! Is there an earlier version that can pull images from the doxie over wifi?

**Comment by ninapavlich** [comment]
Oh yep, that turned out to be very easy. I should have tagged it, but I wasn't thinking. Checkout this commit, this should give you a simple working version that when running will retrieve image from the doxie and move them to a file on your drive:
https://github.com/ninapavlich/doxie-automator/commit/69554567900e7b6c81b41ddaab024b0f5b7b0db5

Let me know if you're interested in collaborating on any of this! I see from your JPEGtoPDFtools project that you have PDFs on your brain too :)

**Comment by LaserTron** [comment]
Hi @ninapavlich I only got around to trying it out this morning. (I'm busy.) I can confirm that it works for downloading and removing jpg files from the Doxie. Thank you!!

For pdf files there seem to be problems, having to do with he fact that the Doxie makes slighlty weird pdf files (pillow gets angry) you may have fixed this in a later commit. Does an even earlier version simply download the files? If not I think I can modify the code for this more basic functionality.

I may be interested in collaborating, but only in a few months.
